language: python
python:
  - "2.6"
  - "2.7"
branches:
  only:
    - master
install:
  - "mkdir /tmp/bin"
  - "cp bin/goferd /tmp/bin/goferd"
  - "pip install iniparse"
  - "pip install src/"
script: nosetests test/unit